### ISSUE TITLE
你B站密码明晃晃的写在了setting里

### ISSUE THREAD

**Issue by nokosan** [CHNLS/GeeTestVerificationCode#1]
你B站密码明晃晃的写在了setting里

**Comment by CHNLS** [comment]
谢谢提醒，之前想改好点的，结果又出问题了，本来想先提交后来再改的，一直没去弄

**Comment by chnls17** [comment]
> 你B站密码明晃晃的写在了setting里

谢谢提醒，之前想改好点的，结果又出问题了，本来想先提交后来再改的，一直没去弄
